### PR TITLE
T03 register page

### PR DESCRIPTION
**Pull request by AymenBerb**
Hello dear reviewers,

I have finished the register page and merged master to my branch.

For testing, I created a unit test for widget testing in the test folder and an integration testing in the integration_test folder (Run 'flutter test integration_test/registration_test.dart').

Play around the register page and lmk if there is something I need to do. 

BTW @AryamanDubey28 I created a key for the sign up button of the login page for my tests, so please don't touch it.

Thanks

### CODE REVIEW

**Review by AryamanDubey28 — DISMISSED** [review]
Hi Aymen, good work!
Well written clean code, well done on going above and beyond! 
Good work testing as well, excellent work!
Before merging could you just pull from my branch as there's some small changes I have made, mainly usage of the 'Auth' class to interact with Firebase authentication

Thanks,
Aryaman

**Comment by AymenBerb** [comment]
@AryamanDubey28 I am not using your Auth class since for idk what reason, it doesnt detect when an email is already in use. And the register page widgets test doest pass.

**Review by Ali-Alkhars — APPROVED** [review]
Well done! Thanks for making the changes

**Review by dmunipi1 — APPROVED** [review]
Good job Aymen, nicely done

**Pull request merged**
