### PR TITLE
T04 admin home UI

### PR DESCRIPTION
**Pull request by Ali-Alkhars**
Hello habibis! T04 is supposed to be done.

### The task was basically the following:
- Build the UI of the page where the admin edits the choice boards
- Build a side-menu that will be used throughout the admin's side of the app.

### Here is what I did in short:
- Created some file structure (pages and models folders)
- A root app for the admin UI "admin_interface" (Choice boards is the home page)
- The choice boards page with some mock data (the buttons do nothing for now)
- A draggable-list model that is used in the choice boards page
- The side-menu widget
- Automated tests for the side menu widget and choice board page

### CODE REVIEW

**Review by AryamanDubey28 — APPROVED** [review]
This is great work Ali, you have written clean and elegant code and have handled testing quite well. Only thing I would say to change is to just delete the old comments about the counter from main.dart

But apart from that, great work

Aryaman

**Comment by AymenBerb** [comment]
Hello Ali, 

That is great work congrats ! 

Please make sure to remove the widget_test.dart file that belongs to the built-in counter app.

I noticed that the ordering isn't saved when reloading the choice board. I was wondering if this was voluntary or not ?  

Thanks for the work

**Comment by Ali-Alkhars** [comment]
> This is great work Ali, you have written clean and elegant code and have handled testing quite well. Only thing I would say to change is to just delete the old comments about the counter from main.dart
> 
> But apart from that, great work
> 
> Aryaman

Changes done!

**Comment by Ali-Alkhars** [comment]
> Hello Ali,
> 
> That is great work congrats !
> 
> Please make sure to remove the widget_test.dart file that belongs to the built-in counter app.
> 
> I noticed that the ordering isn't saved when reloading the choice board. I was wondering if this was voluntary or not ?
> 
> Thanks for the work

Test file removed! About the ordering, it's not supposed to save it now because that would need the database. This task was only UI so

**Review by AymenBerb — APPROVED** [review]

**Pull request merged**
