### PR TITLE
T06 child board UI

### PR DESCRIPTION
**Pull request by dmunipi1**
Dear collaborators,

I've finished T06 and instead of the pictures to zoom on click, the page blurs out. Unfortunately Flutter doesn't allow for it to be zoomed (from what I've read). 

**This task is concerned only with UI design!**
**Build the page that the child would see when clicking a category:**
Pictures should be large
Pictures should be clickable
There should be a “back” button somewhere
When clicking on image, page blurs except for image
Display category name and image

Thanks for your time,
comments are appreciated

### CODE REVIEW

**Review by absirgue — COMMENTED** [review]
Hey,

Looks good to me, thanks!

Too bad that pictures can't be made bigger. I like the blurring I think it's already pretty clear but we can show it to the client during our next meeting and if it needs to also be made bigger we'll have to find a solution then. 

I think tests are good don't know if you could have tested much more.

2 things that are more comments that requests for change though:
1. How easy is it to make this get its data from the database? Would be nice to maybe add a method somewhere that gets a list of (fake for now) objects with a name, an illustration URL, and a rank and return a list of ClickableImages than then can be passed on directly to your UI. Like this we will gain a lot of time when connecting ur thing to the DB
2. Even though colors are not really a problem for now, I think you can remove one of the red or blue (either make the part with title and category image the same color as the rest of the page and the arrow a different one or the arrow the same color than the category image and category title thingy that itself has a different color from the rest of the page). We will be giving the ability for the user to customize the colors and having a little total number of colors (1-3) will make it easier for them to understand what they are doing (if we have to give them the option to "modify the color of the arrow" it's a bit weird). 

Apart from that all good for me with my little Flutter experience for now but happy to know what other people that did Flutter this spirit think.

Thanks for the work!

**Review by skellyhoe — CHANGES_REQUESTED** [review]
Lovely work habibi. 

All is good. However, consider the following changes: 

- Add comments on the child_board.dart file to explain what everything does.
- Try to split widgets that might be reused in other places in the app (like getMainImages()) into their own file (in lib/widgets).

**Comment by dmunipi1** [comment]
Hey, just finished the requested changes please feel free to have a look.

**Review by skellyhoe — APPROVED** [review]
Perfect. Dua lipa would be proud.

**Review by Ali-Alkhars — APPROVED** [review]
Nice work Dion! Also, I heard something about Dua Lipa???

**Pull request merged**
